### ISSUE TITLE
[Slack Alerts] Change Header to only include Rule Name

### ISSUE THREAD

**Issue by natalysheinin** [Issif/falcosidekick#15]
Currently, if your falco rule output is fairly long, each slack alert by falcosidekick will spit out a really ugly json blob (even though that information is already captured in the slack event right below).

I think it may make sense to change it to be just the rule name or configurable via environment variables.

![image](https://user-images.githubusercontent.com/6011550/57404863-07758780-71ab-11e9-96f5-7284c5f8c7f1.png)

**Comment by Issif** [comment]
Hi,

Do you mean something like that?

![image](https://user-images.githubusercontent.com/4520100/57438411-26742800-7244-11e9-8512-9fc364cf9b40.png)

I can add an variable `SLACK_DETAILED_FIELDS=(true|false)` to handle that.

**Comment by Issif** [comment]
merged with #18

**Comment by Issif** [comment]
fixed by #19
