### ISSUE TITLE
Include dateformat suffix to Elasticsearch indices

### ISSUE THREAD

**Issue by ariguillegp** [Issif/falcosidekick#27]
It is really helpful to have indices that can group data on a daily, monthly or annually basis. Here we have some examples:
Daily index: sample-2019.06.24
Monthly index: sample-2019.06
Annual index: sample-2019

**Comment by Issif** [comment]
Hi,

Thanks for your issue, I agree you, I already had that in mind and got several ideas for implement it.

Will do it asap.

**Comment by Issif** [comment]
@ariguillegp I just pushed a new branch https://github.com/Issif/falcosidekick/tree/suffix_elasticsearch

Please test docker image with tag `suffix_elasticsearch`, details are in README of branch.

For now, it's UTC only, do you need timezoning for rotations?

**Comment by ariguillegp** [comment]
Thanks, I just tested the image and the only problem I found was with the monthly indices. That's why I am proposing https://github.com/Issif/falcosidekick/pull/28

**Comment by Issif** [comment]
I rebased with your commit, thanks. If ok for you, I'm releasing a new version.

**Comment by ariguillegp** [comment]
Tested again and it works fine! Thanks
