### ISSUE TITLE
Add Microsoft Teams integration

### ISSUE THREAD

**Issue by aaronmlucas** [Issif/falcosidekick#30]
**What would you like to be added**:
native Microsoft Teams integration to allow for pushing alerts to the chat platform

**Why is this needed**:
Currently the program_output example isn't accepted by MS teams:
`[plundering-grasshopper-falco-jfjp9] Invalid webhook request - Empty Payload18:16:22.370929225: Notice A shell was spawned in a container with an attached terminal (user=<NA> k8s.ns=default k8s.pod=edgy-iguana-mariadb-0 container=791fa4a27927 shell=bash parent=docker-runc cmdline=bash terminal=34817 container_id=791fa4a27927 image=bitnami/mariadb)
[plundering-grasshopper-falco-jfjp9] parse error: Expected string key before ':' at line 1, column 3`

**Comment by Issif** [comment]
Seems good for you? Any idea to improve the design?

![image](https://user-images.githubusercontent.com/4520100/62823960-9f628300-bb97-11e9-86cd-c6d0bad1cc7d.png)

**Comment by aaronmlucas** [comment]
This looks good to me, mapping the values out will be useful.

**Comment by Issif** [comment]
available in release 2.5.0
